version: '3.1'
services:
  stats-client:
    build: statistics/stats-client
    container_name: stats-client
    ports:
      - "9091:9091"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090

  stats-server:
    build: statistics/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics
      - SPRING_DATASOURCE_USER=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root